# Generated by Django 4.2.5 on 2023-09-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
